import argparse
import difflib
import json
import os
import re
import shutil
import sys
from pathlib import Path
from typing import Final

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()
ROOT_DIR: Final[Path] = Path(__file__).resolve().parents[2]
CODEX_RULE_MARKER: Final[str] = "# Generated by agent_sync from .agents/rules/"
AGENTS_DIR: Final[Path] = ROOT_DIR / ".agents"
SETTINGS_DIR: Final[Path] = AGENTS_DIR / "settings"
MODELS_DIR: Final[Path] = AGENTS_DIR / "models"
MAX_DIFF_LINES: Final[int] = 20
SAFE_SLUG_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
NUMBERED_COPY_PATTERN: Final[re.Pattern[str]] = re.compile(r" \d+$")
TEXT_CACHE: dict[Path, str | None] = {}


class FrontMatterDumper(yaml.SafeDumper):
    """SafeDumper variant that renders multiline strings as literal blocks."""


def represent_multiline_str(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    """Render strings containing newlines with literal block style."""

    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


FrontMatterDumper.add_representer(str, represent_multiline_str)


class OutputFile(BaseModel):
    model_config = ConfigDict(frozen=True)

    target_path: Path
    content: str
    kind: str
    slug: str
    source_path: Path | None
    link_target: Path | None = None


class DiffEntry(BaseModel):
    model_config = ConfigDict(frozen=True)

    output: OutputFile
    existing: str | None


class PlatformSettings(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    model: str | None = None


class AgentModelOverride(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    claude: str | None = None
    cursor: str | None = None
    codex: str | None = None


class SkillFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    name: str | None = None
    description: str | None = None


class CommandFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True, populate_by_name=True)

    allowed_tools: str | None = Field(default=None, alias="allowed-tools")
    variants: dict[str, str] | None = None


class AgentFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    name: str | None = None
    description: str | None = None
    tools: str | None = None
    model: str | None = None


class RuleFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True, populate_by_name=True)

    description: str | None = None
    globs: str | list[str] | None = None
    always_apply: bool = Field(default=True, alias="alwaysApply")
    starlark: str | None = None


def main() -> int:
    parser = argparse.ArgumentParser(description="Sync .agents into Claude/Cursor/Codex folders.")
    parser.add_argument("--dry-run", action="store_true", help="Report diffs without writing.")
    args = parser.parse_args()

    if not AGENTS_DIR.exists():
        console.print(f"[red]Error:[/red] Missing .agents directory in {ROOT_DIR}")
        return 2

    platform_settings = load_platform_settings()
    agent_model_overrides = load_agent_model_overrides()
    outputs = generate_outputs(platform_settings, agent_model_overrides)
    diffs = compute_diffs(outputs)
    stale_paths = compute_stale_paths(outputs, platform_settings)

    if not diffs and not stale_paths:
        console.print(Panel("No differences found.", style="green"))
        return 0

    if args.dry_run:
        report_diffs(diffs, stale_paths)
        return 1

    for diff in diffs:
        if diff.output.link_target is not None:
            continue
        write_text(diff.output.target_path, diff.output.content)
        status = "created" if diff.existing is None else "updated"
        console.print(f"  [green]✓[/green] {status}: {diff.output.target_path}")

    for diff in diffs:
        if diff.output.link_target is None:
            continue
        write_symlink(diff.output.target_path, diff.output.link_target)
        console.print(
            f"  [green]✓[/green] linked: {diff.output.target_path} -> {expected_link_text(diff.output)}"
        )

    for stale_path in stale_paths:
        delete_path(stale_path)
        console.print(f"  [green]✓[/green] deleted: {stale_path}")

    dedupe_outputs()

    console.print()
    console.print(
        Panel(
            f"Sync complete. {len(diffs)} file(s) written, {len(stale_paths)} stale path(s) deleted.",
            style="green",
        )
    )
    return 0


def load_json_object(path: Path, model: type[BaseModel]) -> dict | None:
    """Read a JSON object from `path` and validate it against `model`, warning and returning None on failure."""

    raw = read_text(path)
    if raw is None:
        return None

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        console.print(f"[yellow]Warning:[/yellow] Invalid JSON in {path}: {exc}")
        return None

    if not isinstance(data, dict):
        console.print(f"[yellow]Warning:[/yellow] {path} is not a JSON object; ignoring.")
        return None

    return validate_front_matter(data, model, str(path))


def load_platform_settings() -> dict[str, dict]:
    """Load each `.agents/settings/<platform>.json`, validating its top-level shape."""

    settings: dict[str, dict] = {}
    if not SETTINGS_DIR.exists():
        return settings

    for path in sorted(SETTINGS_DIR.glob("*.json")):
        data = load_json_object(path, PlatformSettings)
        if data is not None:
            settings[path.stem] = data

    return settings


def load_agent_model_overrides() -> dict[str, dict[str, str]]:
    """Load each `.agents/models/<agent-slug>.json` mapping agent slug to per-platform model."""

    overrides: dict[str, dict[str, str]] = {}
    if not MODELS_DIR.exists():
        return overrides

    for path in sorted(MODELS_DIR.glob("*.json")):
        slug = validate_slug(path.stem, path)
        data = load_json_object(path, AgentModelOverride)
        if data is not None:
            overrides[slug] = {k: v for k, v in data.items() if isinstance(v, str) and v}

    return overrides


def validate_front_matter(data: dict, model: type[BaseModel], source: str) -> dict | None:
    """Validate front matter data against a Pydantic model. Returns None on failure so callers can skip."""

    try:
        model.model_validate(data)
    except ValidationError as exc:
        console.print(f"[yellow]Warning:[/yellow] Invalid front matter in {source}: {exc}")
        return None

    return data


def parse_markdown_file(path: Path, model: type[BaseModel] | None = None) -> tuple[dict, str]:
    """Parse markdown front matter and body content."""

    content = read_text(path)
    if content is None:
        return {}, ""

    front_matter: dict = {}
    body = content

    lines = content.splitlines()
    if lines and lines[0] == "---":
        end_index = -1
        for index, line in enumerate(lines[1:], start=1):
            if line == "---":
                end_index = index
                break

        if end_index == -1:
            console.print(f"[yellow]Warning:[/yellow] Unterminated front matter in {path}.")
        else:
            front_matter_content = "\n".join(lines[1:end_index]).strip()
            body = "\n".join(lines[end_index + 1 :])
            if front_matter_content:
                raw_data = yaml.safe_load(front_matter_content) or {}
                if not isinstance(raw_data, dict):
                    console.print(f"[yellow]Warning:[/yellow] Invalid front matter in {path}.")
                elif model is None:
                    front_matter = raw_data
                else:
                    front_matter = validate_front_matter(raw_data, model, str(path)) or {}

    return front_matter, normalize_text(body)


def generate_outputs(
    platform_settings: dict[str, dict],
    agent_model_overrides: dict[str, dict[str, str]],
) -> list[OutputFile]:
    """Generate all output files from .agents sources."""

    outputs: list[OutputFile] = []
    outputs.extend(generate_skill_outputs())
    outputs.extend(generate_command_outputs())
    outputs.extend(generate_agent_outputs(platform_settings, agent_model_overrides))
    outputs.extend(generate_rule_outputs())
    outputs.extend(generate_hook_outputs())
    outputs.extend(generate_settings_outputs(platform_settings))
    return outputs


def generate_skill_outputs() -> list[OutputFile]:
    """Sync .agents/skills/<slug>/SKILL.md to .claude/skills/, .cursor/skills/, and .codex/skills/."""

    outputs: list[OutputFile] = []
    skills_dir = AGENTS_DIR / "skills"
    if not skills_dir.exists():
        return outputs

    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue

        slug = validate_slug(skill_dir.name, skill_dir)
        source_path = skill_dir / "SKILL.md"
        if not source_path.exists():
            console.print(f"[yellow]Warning:[/yellow] Missing SKILL.md in {skill_dir}.")
            continue

        front_matter, content = parse_markdown_file(source_path, SkillFrontMatter)

        codex_name = nonempty_str(front_matter.get("name")) or slug_to_codex_name(slug)
        if not SAFE_SLUG_PATTERN.match(codex_name):
            console.print(
                f"[yellow]Warning:[/yellow] Invalid codex skill name '{codex_name}' in {source_path}; using '{slug_to_codex_name(slug)}'."
            )
            codex_name = slug_to_codex_name(slug)

        codex_description = nonempty_str(front_matter.get("description")) or derive_description(content)

        # Claude and Cursor read the source skill directory through relative
        # links; only Codex needs a transformed physical copy.
        for platform in ("claude", "cursor"):
            outputs.append(
                OutputFile(
                    target_path=ROOT_DIR / f".{platform}" / "skills" / slug,
                    content="",
                    kind=f"{platform}_skill",
                    slug=slug,
                    source_path=source_path,
                    link_target=skill_dir,
                )
            )

        outputs.append(
            OutputFile(
                target_path=ROOT_DIR / ".codex" / "skills" / codex_name / "SKILL.md",
                content=assemble_codex_skill(content, codex_name, codex_description),
                kind="codex_skill",
                slug=slug,
                source_path=source_path,
            )
        )

        for asset_path in sorted(skill_dir.rglob("*")):
            if not asset_path.is_file() or asset_path.name == "SKILL.md":
                continue
            asset_content = read_text(asset_path)
            if asset_content is None:
                continue
            relative = asset_path.relative_to(skill_dir)
            outputs.append(
                OutputFile(
                    target_path=ROOT_DIR / ".codex" / "skills" / codex_name / relative,
                    content=ensure_trailing_newline(asset_content),
                    kind="codex_skill_asset",
                    slug=slug,
                    source_path=asset_path,
                )
            )

    return outputs


def generate_command_outputs() -> list[OutputFile]:
    """Generate Claude and Cursor command files for each command markdown file."""

    outputs: list[OutputFile] = []
    commands_dir = AGENTS_DIR / "commands"
    if not commands_dir.exists():
        return outputs

    for path in sorted(commands_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, content = parse_markdown_file(path, CommandFrontMatter)
        raw_variants = front_matter.get("variants")
        variants = raw_variants if isinstance(raw_variants, dict) else {}

        claude_body = normalize_text(variants.get("claude", content) or content)
        cursor_body = normalize_text(variants.get("cursor", content) or content)
        claude_front_matter = dict(front_matter)
        claude_front_matter.pop("variants", None)

        if claude_front_matter:
            claude_output = render_front_matter(claude_front_matter, claude_body)
        else:
            claude_output = ensure_trailing_newline(claude_body)

        outputs.append(
            OutputFile(
                target_path=ROOT_DIR / ".claude" / "commands" / f"{slug}.md",
                content=claude_output,
                kind="claude_command",
                slug=slug,
                source_path=path,
            )
        )
        outputs.append(
            OutputFile(
                target_path=ROOT_DIR / ".cursor" / "commands" / f"{slug}.md",
                content=ensure_trailing_newline(cursor_body),
                kind="cursor_command",
                slug=slug,
                source_path=path,
            )
        )

    return outputs


def generate_agent_outputs(
    platform_settings: dict[str, dict],
    agent_model_overrides: dict[str, dict[str, str]],
) -> list[OutputFile]:
    """Generate Claude and Cursor agent files with per-platform model resolution."""

    outputs: list[OutputFile] = []
    agents_dir = AGENTS_DIR / "agents"
    if not agents_dir.exists():
        return outputs

    for path in sorted(agents_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, content = parse_markdown_file(path, AgentFrontMatter)
        source_front_matter = dict(front_matter)
        source_front_matter.pop("model", None)

        for platform in ("claude", "cursor"):
            platform_front_matter = dict(source_front_matter)
            model = resolve_agent_model(slug, platform, platform_settings, agent_model_overrides)
            if model:
                platform_front_matter["model"] = model

            agent_content = render_front_matter(platform_front_matter, content)
            outputs.append(
                OutputFile(
                    target_path=ROOT_DIR / f".{platform}" / "agents" / f"{slug}.md",
                    content=agent_content,
                    kind=f"{platform}_agent",
                    slug=slug,
                    source_path=path,
                )
            )

    return outputs


def generate_rule_outputs() -> list[OutputFile]:
    """Normalize .agents/rules/<name>.md in place, link Claude/Cursor rule paths to it, and emit Starlark .codex/rules/*.rules."""

    outputs: list[OutputFile] = []
    rules_dir = AGENTS_DIR / "rules"
    if not rules_dir.exists():
        return outputs

    for path in sorted(rules_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, body = parse_markdown_file(path, RuleFrontMatter)
        if body.strip():
            outputs.append(
                OutputFile(
                    target_path=path,
                    content=normalize_rule_source(front_matter, body),
                    kind="agents_rule",
                    slug=slug,
                    source_path=path,
                )
            )
            for platform, filename in (("claude", f"{slug}.md"), ("cursor", f"{slug}.mdc")):
                outputs.append(
                    OutputFile(
                        target_path=ROOT_DIR / f".{platform}" / "rules" / filename,
                        content="",
                        kind=f"{platform}_rule",
                        slug=slug,
                        source_path=path,
                        link_target=path,
                    )
                )

        # Codex execution-policy files must be Starlark, not Markdown. Only emit
        # when the source explicitly provides `starlark:` front matter; otherwise
        # skip silently — the Markdown body is not valid policy syntax. The marker
        # comment lets compute_stale_paths prune synced files while leaving
        # hand-maintained Starlark policies alone.
        starlark = front_matter.get("starlark")
        if isinstance(starlark, str) and starlark.strip():
            content = f"{CODEX_RULE_MARKER}{path.name}\n{starlark.strip()}"
            outputs.append(
                OutputFile(
                    target_path=ROOT_DIR / ".codex" / "rules" / f"{slug}.rules",
                    content=ensure_trailing_newline(content),
                    kind="codex_rule",
                    slug=slug,
                    source_path=path,
                )
            )

    return outputs


def generate_hook_outputs() -> list[OutputFile]:
    """Sync .agents/hooks/* scripts to .claude/hooks/ and .cursor/hooks/."""

    outputs: list[OutputFile] = []
    hooks_dir = AGENTS_DIR / "hooks"
    if not hooks_dir.exists():
        return outputs

    for path in sorted(hooks_dir.iterdir()):
        if not path.is_file():
            continue
        content = read_text(path)
        if content is None:
            continue
        for platform in ("claude", "cursor"):
            outputs.append(
                OutputFile(
                    target_path=ROOT_DIR / f".{platform}" / "hooks" / path.name,
                    content=ensure_trailing_newline(content),
                    kind=f"{platform}_hook",
                    slug=path.stem,
                    source_path=path,
                )
            )

    return outputs


def generate_settings_outputs(platform_settings: dict[str, dict]) -> list[OutputFile]:
    """Sync .agents/settings/claude.json verbatim to .claude/settings.json."""

    outputs: list[OutputFile] = []
    claude_settings = platform_settings.get("claude")
    if claude_settings is None:
        return outputs

    outputs.append(
        OutputFile(
            target_path=ROOT_DIR / ".claude" / "settings.json",
            content=ensure_trailing_newline(json.dumps(claude_settings, indent=2)),
            kind="claude_settings",
            slug="claude",
            source_path=SETTINGS_DIR / "claude.json",
        )
    )

    return outputs


def normalize_rule_source(front_matter: dict, body: str) -> str:
    """Rebuild a rule source file with unified, deterministically ordered front matter."""

    normalized: dict = {}
    for key in ("description", "globs"):
        value = front_matter.get(key)
        if value:
            normalized[key] = value

    always_apply = front_matter.get("alwaysApply")
    normalized["alwaysApply"] = always_apply if isinstance(always_apply, bool) else True

    starlark = front_matter.get("starlark")
    if isinstance(starlark, str) and starlark.strip():
        normalized["starlark"] = starlark

    known_keys = {"name", "description", "globs", "alwaysApply", "starlark"}
    for key in sorted(set(front_matter) - known_keys):
        normalized[key] = front_matter[key]

    return render_front_matter(normalized, body)


def assemble_codex_skill(body: str, name: str, description: str) -> str:
    """Build a Codex SKILL.md file with name/description front matter."""

    front_matter = "---\n" f"name: {yaml_quote(name)}\n" f"description: {yaml_quote(description)}\n" "---\n\n"
    return front_matter + ensure_trailing_newline(body)


def render_front_matter(front_matter: dict, body: str) -> str:
    """Serialize a dict as YAML front matter wrapped in --- delimiters."""

    if front_matter:
        front = yaml.dump(
            front_matter,
            Dumper=FrontMatterDumper,
            sort_keys=False,
            default_flow_style=False,
            width=10_000,
            allow_unicode=True,
        ).strip()
    else:
        front = ""

    output = f"---\n{front}\n---\n"
    if body:
        output += "\n" + body

    return ensure_trailing_newline(output)


def nonempty_str(value: object) -> str | None:
    """Return value when it is a non-empty string, else None."""

    return value if isinstance(value, str) and value else None


def normalize_text(value: object) -> str:
    if not isinstance(value, str):
        return ""
    return value.strip()


def slug_to_codex_name(slug: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9]+", "-", slug).strip("-").lower()
    return normalized or slug


def derive_description(content: str) -> str:
    """Extract a description from content, preferring the first non-header line then falling back to the first header."""

    first_header: str | None = None
    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("#"):
            if first_header is None:
                first_header = " ".join(line.lstrip("#").strip().split())
            continue
        return " ".join(line.split())

    return first_header if first_header is not None else "Project conventions."


def ensure_trailing_newline(text: str) -> str:
    return text if text.endswith("\n") else text + "\n"


def compute_diffs(outputs: list[OutputFile]) -> list[DiffEntry]:
    """Compare generated outputs and symlinks against on-disk state and return differing entries."""

    diffs: list[DiffEntry] = []
    for output in outputs:
        if output.link_target is not None:
            existing_link = read_link(output.target_path)
            if existing_link != expected_link_text(output):
                diffs.append(DiffEntry(output=output, existing=existing_link))
            continue

        existing = read_text(output.target_path)
        if existing is None or existing != output.content or missing_exec_bit(output):
            diffs.append(DiffEntry(output=output, existing=existing))
    return diffs


def expected_link_text(output: OutputFile) -> str:
    """Return the relative symlink text a link output should carry on disk."""

    assert output.link_target is not None
    return os.path.relpath(output.link_target, output.target_path.parent)


def is_executable_output(path: Path, content: str) -> bool:
    """Report whether an output should carry the exec bit (shell scripts and shebang files)."""

    return path.suffix == ".sh" or content.startswith("#!")


def missing_exec_bit(output: OutputFile) -> bool:
    """Report whether an executable output exists on disk without its exec bit, so write_text re-applies chmod."""

    target = output.target_path
    if not is_executable_output(target, output.content):
        return False
    return target.exists() and not target.stat().st_mode & 0o111


def compute_stale_paths(
    outputs: list[OutputFile],
    platform_settings: dict[str, dict],
) -> list[Path]:
    """Find generated files/directories that no longer map to .agents sources."""

    skill_kinds = {"codex_skill", "claude_skill", "cursor_skill"}
    expected_paths = {output.target_path for output in outputs}
    linked_dirs = {
        output.target_path
        for output in outputs
        if output.link_target is not None and output.kind in skill_kinds
    }
    expected_skill_dirs = linked_dirs | {
        output.target_path.parent
        for output in outputs
        if output.kind in skill_kinds and output.link_target is None
    }
    stale_paths: set[Path] = set()

    managed_file_globs = (
        (ROOT_DIR / ".cursor" / "rules", "*.mdc"),
        (ROOT_DIR / ".claude" / "rules", "*.md"),
        (ROOT_DIR / ".cursor" / "commands", "*.md"),
        (ROOT_DIR / ".claude" / "commands", "*.md"),
        (ROOT_DIR / ".cursor" / "agents", "*.md"),
        (ROOT_DIR / ".claude" / "agents", "*.md"),
        (ROOT_DIR / ".cursor" / "hooks", "*"),
        (ROOT_DIR / ".claude" / "hooks", "*"),
        # Skills use `**/*` so non-markdown assets (metadata.json, scripts, plugin
        # manifests, etc.) get cleaned up when removed from .agents/skills/.
        (ROOT_DIR / ".cursor" / "skills", "**/*"),
        (ROOT_DIR / ".claude" / "skills", "**/*"),
        (ROOT_DIR / ".codex" / "skills", "**/*"),
    )

    for directory, pattern in managed_file_globs:
        if not directory.exists():
            continue

        for path in directory.glob(pattern):
            if any(linked in path.parents for linked in linked_dirs):
                continue
            if (path.is_file() or path.is_symlink()) and path not in expected_paths:
                stale_paths.add(path)

    # `.codex/rules/*.rules` are only managed when the file carries the sync
    # marker on its first line. Hand-maintained Starlark policies without the
    # marker are left alone; previously-synced orphans (source removed) get
    # cleaned up because they still carry the marker.
    codex_rules_dir = ROOT_DIR / ".codex" / "rules"
    if codex_rules_dir.exists():
        for path in codex_rules_dir.glob("*.rules"):
            if not path.is_file() or path in expected_paths:
                continue
            head = read_text(path)
            if head is not None and head.startswith(CODEX_RULE_MARKER):
                stale_paths.add(path)

    # .claude/settings.json is only "managed" when its source loaded successfully —
    # an invalid claude.json must NOT trigger deletion of the deployed settings
    # (which would remove the Stop hook etc.).
    settings_path = ROOT_DIR / ".claude" / "settings.json"
    if "claude" in platform_settings and settings_path.exists() and settings_path not in expected_paths:
        stale_paths.add(settings_path)

    # Note: we deliberately don't auto-delete legacy generated files (e.g. an old
    # root `.codex.md`). Codex's `config.toml` may still reference it as a
    # project-doc fallback, and a hand-maintained copy is the user's to remove.

    for platform in ("codex", "claude", "cursor"):
        skills_dir = ROOT_DIR / f".{platform}" / "skills"
        if not skills_dir.exists():
            continue
        for path in skills_dir.iterdir():
            if (path.is_dir() or path.is_symlink()) and path not in expected_skill_dirs:
                stale_paths.add(path)

    return sorted(stale_paths, key=str)


def read_text(path: Path) -> str | None:
    """Read a file with caching to avoid repeated disk reads."""

    if path in TEXT_CACHE:
        return TEXT_CACHE[path]

    if not path.exists():
        TEXT_CACHE[path] = None
        return None

    content = path.read_text(encoding="utf-8")
    TEXT_CACHE[path] = content
    return content


def write_text(path: Path, content: str) -> None:
    """Write content to a file, creating parent directories and updating the read cache."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        path.unlink()
    path.write_text(content, encoding="utf-8")
    if is_executable_output(path, content):
        path.chmod(0o755)
    TEXT_CACHE[path] = content


def write_symlink(path: Path, target: Path) -> None:
    """Create a relative symlink at path pointing to target, replacing any existing entry."""

    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink() or path.exists():
        delete_path(path)
    path.symlink_to(os.path.relpath(target, path.parent))
    TEXT_CACHE.pop(path, None)


def read_link(path: Path) -> str | None:
    """Return the symlink target text for path, or None when it is not a symlink."""

    if not path.is_symlink():
        return None
    return os.readlink(path)


def delete_path(path: Path) -> None:
    """Delete a file, directory, or symlink and clear any cached text entries."""

    if path.is_symlink():
        path.unlink()
        TEXT_CACHE.pop(path, None)
        return

    if not path.exists():
        return

    if path.is_dir():
        shutil.rmtree(path)
        stale_keys = [cached_path for cached_path in TEXT_CACHE if cached_path.is_relative_to(path)]
        for stale_key in stale_keys:
            TEXT_CACHE.pop(stale_key, None)
        return

    path.unlink(missing_ok=True)
    TEXT_CACHE.pop(path, None)


def report_diffs(diffs: list[DiffEntry], stale_paths: list[Path]) -> None:
    console.print(Panel("Differences detected", style="yellow"))
    table = Table(show_header=True, header_style="bold")
    table.add_column("Target")
    table.add_column("Kind")
    table.add_column("Status")

    for diff in diffs:
        status = "missing" if diff.existing is None else "changed"
        table.add_row(str(diff.output.target_path), diff.output.kind, status)

    for stale_path in stale_paths:
        if stale_path.is_symlink():
            kind = "symlink"
        elif stale_path.is_dir():
            kind = "directory"
        else:
            kind = "generated"
        table.add_row(str(stale_path), kind, "stale")

    console.print(table)

    for diff in diffs:
        console.print()
        console.print(Panel(diff_summary(diff), title=str(diff.output.target_path)))

    for stale_path in stale_paths:
        console.print()
        console.print(Panel("will be deleted", title=str(stale_path)))


def diff_summary(diff: DiffEntry) -> str:
    """Produce a unified diff between existing and expected content."""

    if diff.output.link_target is not None:
        return f"symlink -> {expected_link_text(diff.output)}"

    existing = diff.existing or ""
    expected = diff.output.content
    lines = list(
        difflib.unified_diff(
            existing.splitlines(),
            expected.splitlines(),
            fromfile="current",
            tofile="expected",
            lineterm="",
        )
    )

    if not lines:
        if existing != expected:
            return "(trailing newline difference)"
        return "(no changes)"

    return "\n".join(lines[:MAX_DIFF_LINES])


def resolve_agent_model(
    agent_slug: str,
    platform: str,
    platform_settings: dict[str, dict],
    agent_model_overrides: dict[str, dict[str, str]],
) -> str | None:
    """Pick the per-agent override for this platform; fall back to the platform-wide default."""

    override = agent_model_overrides.get(agent_slug, {}).get(platform)
    default = platform_settings.get(platform, {}).get("model")

    return nonempty_str(override) or nonempty_str(default)


def validate_slug(slug: str, source_path: Path) -> str:
    if not SAFE_SLUG_PATTERN.match(slug):
        raise ValueError(f"Invalid slug '{slug}' from {source_path}")
    return slug


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def dedupe_outputs() -> None:
    for directory in (ROOT_DIR / ".cursor" / "rules", ROOT_DIR / ".claude" / "rules"):
        dedupe_directory(directory)


def dedupe_directory(directory: Path) -> None:
    """Remove OS-created duplicate files whose name ends with a space and a number (e.g. "name 2.md")."""

    if not directory.exists():
        return

    for path in sorted(directory.iterdir()):
        if path.is_file() and NUMBERED_COPY_PATTERN.search(path.stem):
            path.unlink(missing_ok=True)
            TEXT_CACHE.pop(path, None)


if __name__ == "__main__":
    sys.exit(main())
